name: Post Merge Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  all_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cicd_requirements.txt
          TEST_VER=`grep -m 1 TEST_VERSION ./tests/module_import/test_module_import.py | cut -d ' ' -f 3`
          TEST_VER=`echo ${TEST_VER} | cut -d '"' -f 2`
          echo "test_module_import.py TEST_VER=${TEST_VER}"
          bash ./scripts/update_version.sh ${TEST_VER}
          pip install . --no-dependencies
      - name: Run all tests
        run: bash ./scripts/run_tests.sh all
      - name: Run broken link report
        run: python ./scripts/check_links.py

