name: Skip Test Pypi and Publish to Pypi
on:
  workflow_dispatch:
    push:
      tags:
        - 'v*.*.*'

jobs:
  local-install-test:
    name: Build PeekingDuck and test locally
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
      - name: Update Version 
        run: |
          bash ./scripts/update_version.sh $VERSION
